// Generate src/lib/voice/liveTools.generated.ts from the ElevenLabs tool
// definitions in scripts/provision-agent.ts.
// Run: npm run voice:tools
//
// Why a generated file and not an import: provision-agent.ts reads .env.local
// at import time and throws without TOOL_BASE_URL, so runtime code cannot
// import it (textTools.ts avoids it for the same reason). Until phase 4 of the
// GPT-Live migration moves TOOLS here for good, this script is the bridge:
// the ElevenLabs definitions stay the source of truth, and the Responses
// function schema is derived, never hand-edited.
//
// ponytail: transition copy, dies in phase 4 when TOOLS moves to src/lib/voice.
import { writeFileSync } from "node:fs";
import { SYSTEM_TOOLS, TOOLS } from "./provision-agent.ts";
import type { LiveFunctionTool } from "../src/lib/voice/liveToolTypes.ts";

type Schema = { properties?: Record<string, unknown>; required?: string[] };

type ElevenTool = {
  type: "webhook" | "client";
  name: string;
  description: string;
  apiSchema?: { requestBodySchema?: Schema };
  parameters?: Schema;
};

function toFunction(t: ElevenTool): LiveFunctionTool {
  const schema = t.type === "client" ? t.parameters : t.apiSchema?.requestBodySchema;
  return {
    type: "function",
    name: t.name,
    description: t.description,
    parameters: {
      type: "object",
      properties: schema?.properties ?? {},
      required: schema?.required ?? [],
    },
  };
}

// end_call was an ElevenLabs system tool, never a webhook. In GPT-Live it is
// a plain function the browser answers by closing the session. Same words,
// minus the sentence about ElevenLabs' DISENGAGE button.
const endCall = SYSTEM_TOOLS.find((t) => t.name === "end_call");
if (!endCall) throw new Error("end_call missing from SYSTEM_TOOLS");
const END_CALL: LiveFunctionTool = {
  type: "function",
  name: "end_call",
  description: endCall.description.replace(/ He can always end it himself[^.]*\.\s*/, " "),
  parameters: { type: "object", properties: {}, required: [] },
};

const tools = [
  ...(TOOLS as unknown as ElevenTool[]).map(toFunction),
  END_CALL,
];

const out = `// GENERATED by scripts/export-live-tools.ts from scripts/provision-agent.ts.
// Do not edit. Run: npm run voice:tools
import type { LiveFunctionTool } from "./liveToolTypes.ts";

export const LIVE_TOOLS: readonly LiveFunctionTool[] = ${JSON.stringify(tools, null, 2)};
`;

writeFileSync(new URL("../src/lib/voice/liveTools.generated.ts", import.meta.url), out);
console.log(`Wrote src/lib/voice/liveTools.generated.ts — ${tools.length} tools`);
